lutnia/lutnia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path("accounts/login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('admin/', admin.site.urls),
    path('', include('lutnia_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

lutnia/lutnia_app/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from .views import DayView, MonthView, YearView

urlpatterns = [
    path('', views.homepage, name=""),
    #user management
    path('register', views.register, name="register"),
    path('my_login', views.my_login, name="my_login"),
    path('user_logout', views.user_logout, name="user_logout"),
    path('profile', views.profile, name="profile"),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    #tables, excersises and stats
    path('default_table', views.default_table, name="default_table"),
    path('excersises', views.excersises, name="excersises"),
    path('stats', views.stats, name="stats"),
    #youtube vids
    path('youtube', views.youtube, name="youtube"),
    #booking system
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.event, name='event_new'),
    path("event/<int:event_id>/delete/", views.delete_event, name="delete_event"),
    path('event/edit/<int:event_id>/', views.event, name='event_edit'),
    path('calendar/<int:year>/<int:month>/', MonthView.as_view(), name='month_view'),
    #path('calendar/<int:year>/<int:month>/<int:day>/', DayView.as_view(), name='day_view'),
    path('calendar/<int:year>/<int:month>/<int:day>/', views.day_view, name='day_view'),
    path("calendar/<int:year>/", YearView.as_view(), name="year_view"),
    #path("day_view2", views.day_view, name="day_view2"),
    #path("day_view2/<int:year>/<int:month>/<int:day>/", views.day_view2, name="day_view2"),
]

lutnia/lutnia_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.urls import reverse  
from django.core.files.storage import default_storage
from PIL import Image
from django.utils._os import safe_join
from django.conf import settings

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #file_path = safe_join(settings.MEDIA_ROOT, "profile_pics/default.png")
    #print(f'SCIEZKA DO PLIKU TO: {file_path}')
    image = models.ImageField(default="profile_pics/default.png", upload_to="profile_pics/")
    user_code = models.CharField(max_length=2, blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)

    def __str__(self):
        return f'{self.user.last_name} {self.user.first_name} Profile'

    def save(self, *args, **kwargs):
        #default_profile_image = safe_join(settings.MEDIA_ROOT, "profile_pics/default.png")
        """Delete the old image when updating the profile image (except the default image)."""
        try:
            old_profile = Profile.objects.get(pk=self.pk)  # Get existing profile instance
            if old_profile.image and old_profile.image != self.image:
                if old_profile.image.name != "profile_pics/default.png":  # Avoid deleting default image
                    if default_storage.exists(old_profile.image.name):
                        default_storage.delete(old_profile.image.name)  # Delete old image
        except Profile.DoesNotExist:
            pass  # If profile doesn't exist yet, do nothing

        super().save(*args, **kwargs)  # Save new image
        img = Image.open(self.image.path)  # Open image
        if img.height > 300 or img.width > 300:  # Resize if too large
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)  # Overwrite saved image
    
    def delete(self, *args, **kwargs):
        """Delete image file when deleting the profile (except the default image)."""
        if self.image and self.image.name != 'profile_pics/default.png':
            if default_storage.exists(self.image.name):
                default_storage.delete(self.image.name)
        super().delete(*args, **kwargs)

# Signal to delete the image when the profile is deleted
@receiver(models.signals.post_delete, sender=Profile)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes image file from storage when the Profile object is deleted."""
    if instance.image and instance.image.name != 'profile_pics/default.png':
        if default_storage.exists(instance.image.name):
            default_storage.delete(instance.image.name)
   
class YTVideo(models.Model):
    link = models.URLField()
    def __unicode__(self):
        return self.link

class Event(models.Model):
    PLACE_CHOICES = [
        ('1', 'Moniuszki'),
        ('2', 'Laska'),
    ]

    TABLE_CHOICES = [
        ('1', 'Snooker nr.1'),
        ('2', 'Snooker nr.2'),
        ('3', 'Pool nr.1'),
        ('4', 'Pool nr.2'),
        ('5', 'Snooker nr.3'),
        ('6', 'Snooker nr.4'),
        ('7', 'Snooker nr.5'),
    ]

    TABLE_CHOICES_LUTNIA =[
        ('5', 'Snooker nr.3'),
        ('6', 'Snooker nr.4'),
        ('7', 'Snooker nr.5'),
    ]

    BOOKING_TYPE_CHOICES = [
        ("1", "Liga"),
        ("2", "Turniej"),
        ("3", "Trening"),
        ("4", "Moge z kims ragrac"),
        ("5", "Rezerwuje dla 2 osob"),
        ("6", "Szkolka Dorosli"),
        ("7", "Szkolka Dzieci"),
        ("8", "Brak mozliwosci"), 
    ]

    place = models.CharField(max_length=100, default='Moniuszki', choices=PLACE_CHOICES)
    table = models.CharField(max_length=100, default='Sonnker nr.1' , choices=TABLE_CHOICES)
    bookingtype = models.CharField(max_length=100, default='Liga', choices=BOOKING_TYPE_CHOICES)
    user = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    confirmed = models.BooleanField(default=True)
    @property
    def get_html_url(self):
        url = reverse('event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.user.last_name} {self.user.first_name}</a>'
    
    def __str__(self):
        dejt = self.start_time.strftime("%Y-%B-%A-%d")
        plejs = dict(self.PLACE_CHOICES).get(self.place, self.place)
        bt = dict(self.BOOKING_TYPE_CHOICES).get(self.bookingtype, self.bookingtype)
        return f'{self.user.last_name} {self.user.first_name} {dejt} {plejs} {bt}'
   

lutnia/lutnia_app/views.py
import calendar
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.models import auth
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime, date, timedelta
from django.contrib import messages
from django.views import generic
from django.urls import reverse
from .models import *
from .utils import Calendar
from calendar import monthrange
from django.views.generic import TemplateView
from django.utils.timezone import make_naive
from . forms import *
from django.utils import timezone
from django.core.paginator import Paginator

def homepage(request):
    rok = datetime.today().strftime("%Y")
    miesiac = datetime.today().strftime("%m")
    return render(request, 'lutnia_app/index.html', {'year': rok, 'month': miesiac,})

def youtube(request):
    form = YTVideoForm()
    if request.method == "POST":
        form = YTVideoForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Link dodany!')
            return redirect("youtube")
    full_list = YTVideo.objects.all()
    context = {'full_list': full_list, 'form': form,}
    return render(request, 'lutnia_app/youtube.html', context)
    

def register(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Rejestracja zakonczona powodzeniem!')
            return redirect("my_login")
    context = {'registerform': form}
    return render(request, 'lutnia_app/register.html', context=context)

#login
def my_login(request):
    form = LoginForm()
    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                print(user, request)
                return redirect('profile')
    context = {'loginform':form}
    return render(request, 'lutnia_app/my_login.html', context=context)

def user_logout(request):
    auth.logout(request)
    return redirect("")

@login_required(login_url="my_login")
def profile(request):
    my_events = Event.objects.filter(user=request.user).order_by('-start_time')
    pag = Paginator(my_events, 3)
    page = request.GET.get('page')
    event_list = pag.get_page(page)
    context = {'my_events': event_list}
    return render(request, 'lutnia_app/profile.html', context=context)

@login_required(login_url="my_login")
def edit_profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Your profile has been updated!')
            return redirect('profile')  # Redirect to the profile page
        else:
            messages.warning(request, 'Cos poszlo nie tak!!!!!')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {'u_form': u_form, 'p_form': p_form}
    return render(request, 'lutnia_app/edit_profile.html', context)

@login_required(login_url="my_login")
def default_table(request):
    return render(request, 'lutnia_app/tabele/default_table.html')

@login_required(login_url="my_login")
def excersises(request):
    return render(request, 'lutnia_app/excersises.html')

@login_required(login_url="my_login")
def stats(request):
    return render(request, 'lutnia_app/stats.html')

class CalendarView(generic.ListView):
    model = Event
    template_name = 'lutnia_app/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        d = get_date(self.request.GET.get('month'))

        # Instantiate our calendar class with today's year and date
        cal = Calendar(d.year, d.month)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = html_cal
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_month):
    print(f"Received month parameter: {req_month}")
    if req_month:
        try:
            year, month = (int(x) for x in req_month.split('-'))
            return date(year, month, 1)
        except ValueError:
            return datetime.today().date()  # Fallback if parsing fails
    return datetime.today().date()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    return f'month={prev_month.year}-{prev_month.month}'

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    return f'month={next_month.year}-{next_month.month}'

@login_required(login_url="my_login")
def event(request, event_id=None):
    if event_id:  # Editing an existing event
        instance = get_object_or_404(Event, pk=event_id)

        if instance.user != request.user:
            messages.error(request, "Nie mozesz edytowac tej rezerwacji. Nie jestes jej wlascicielem!")
            return redirect('month_view', month=instance.start_time.strftime("%m"), year=instance.start_time.strftime("%Y"))
    else:  # Creating a new event
        instance = Event()
        instance.user = request.user  # Assign the logged-in user as the event creator

    form = EventForm(request.POST or None, instance=instance)
    
    if request.POST and form.is_valid():
        event = form.save(commit=False)  # Don't save yet to modify datetimes
        
        # Ensure start_time and end_time are timezone-aware
        event.start_time = timezone.make_aware(event.start_time) if timezone.is_naive(event.start_time) else event.start_time
        event.end_time = timezone.make_aware(event.end_time) if timezone.is_naive(event.end_time) else event.end_time
        
        event.save()  # Save after ensuring timezone-awareness
        messages.success(request, "Rezerwacja zatwierdzona!")
        return redirect('month_view', month=request.POST['date_month'], year=request.POST['date_year'])

    # Use timezone-aware `now()` instead of `datetime.today()`
    rok = timezone.now().year
    miesiac = timezone.now().month

    return render(request, 'lutnia_app/event.html', {'form': form, 'today_year': rok, 'today_month': miesiac, 'instance': instance})

@login_required(login_url="my_login")
def delete_event(request, event_id):
    event = get_object_or_404(Event, id=event_id)
    rok = datetime.today().strftime("%Y")
    miesiac = datetime.today().strftime("%m")
    if request.method == "POST":  # Confirm delete
        event.delete()
        messages.warning(request, "Rezerwacja zostala usunieta!")
        return redirect("month_view", year=rok, month=miesiac)

    return render(request, "lutnia_app/event_confirm_delete.html", {"event": event, 'year':rok, 'month':miesiac})


def day_view(request, year, month, day):  
    # Generate 24-hour list with 30-minute intervals
    hours = [(datetime(2023, 1, 1, 0, 0) + timedelta(minutes=30 * i)).strftime('%H:%M') for i in range(48)]

    today = datetime(year, month, day)
    prev_day = (today - timedelta(days=1)).strftime("%d")
    next_day = (today + timedelta(days=1)).strftime("%d")
    year = today.year
    month = today.month

    # Fetch events for the specific day
    events = Event.objects.filter(start_time__date=today).order_by('start_time')
    
    hourly_events = {hour: [] for hour in hours}
    for event in events:
        event_start_hour = make_naive(event.start_time).strftime("%H:%M")
        if event_start_hour in hourly_events:
            hourly_events[event_start_hour].append({
                'event': event,
                'duration': event.end_time - event.start_time,
                'edit_url': reverse('event_edit', args=[event.id])
            })
        else:
            print(f"Event start time {event_start_hour} not found in hourly_events keys!")

    context = {
        'year': year,
        'month': month,
        'godziny': hours,
        'events': events,
        'next_day': next_day,
        'prev_day': prev_day,
        'hourly_events': hourly_events,
        'today': today.strftime("%d %B %Y"),
    }
    
    return render(request, 'lutnia_app/day_view2.html', context)


class DayView(TemplateView):
    template_name = "lutnia_app/day_view.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get date from URL or use today
        selected_date = datetime(kwargs['year'], kwargs['month'], kwargs['day']).date()
        prev_day = selected_date - timedelta(days=1)
        next_day = selected_date + timedelta(days=1)
        # Generate list of hours (00:00 - 23:00) with naive datetime
        hours = [datetime(selected_date.year, selected_date.month, selected_date.day, h, 0) for h in range(24)]

        # Fetch events for the selected date
        events = Event.objects.filter(start_time__date=selected_date).order_by('start_time')

        # Ensure dictionary keys match event timestamps (naive datetime)
        hourly_events = {hour: [] for hour in hours}
        for event in events:
            event_start_hour = make_naive(event.start_time)
            if event_start_hour in hourly_events:
                hourly_events[event_start_hour].append({
                    'event': event,

lutnia/lutnia_app/templates/lutnia_app/calendar.html
{% extends "lutnia_app/base.html" %}
{% block content %}
<hr>
<div class="menu btn-group btn-group" role="group" aria-label="Small button group">
  <a class="btn btn-outline-success" href="{% url 'calendar' %}?{{ prev_month }}"> Poprzedni miesiac </a>
  <a class="btn btn-outline-secondary" href="{% url 'event_new' %}">Rezerwacja</a>
	<a class="btn btn-outline-success" href="{% url 'calendar' %}?{{ next_month }}"> Nastepny miesiac </a>
</div>
<hr>
{{ calendar|safe }}
<style>

.calendar {
  width: 100%;
  margin: auto;
  font-size: 13px;
}
.menu {
  width: 100%;
}

.calendar tr, .calendar td {
  border: 1px solid black;
}

.calendar th {
  padding: 10px;
  text-align: center;
  font-size: 18px;
}

.calendar td {
  width: 200px;
  height: 150px;
  padding: 20px 0px 0px 5px;
}

.month {
  font-size: 25px;
}

.date {
  font-size: 16px;
}

ul {
  height: 100%;
  padding: 0px 5px 0px 20px;
}

.left {
  float: left;
}

.right {
  float: right;
}
</style>

{% endblock content %}

lutnia/lutnia_app/templates/lutnia_app/day_view2.html
{% extends "lutnia_app/base.html" %}

{% block content %}
<div class="container">
    <hr>
    <div class="btn-group d-flex">
    <a class="btn btn-outline-dark" href="{% url 'month_view' year=year month=month %}">Miesiac</a>
    <a class="btn btn-outline-dark" href="{% url 'event_new' %}">Rezerwacja</a>
    <a class="btn btn-outline-dark" href="{% url 'year_view' year=year %}">Rok</a>
    </div>
    <hr>
    <div class="btn-group d-flex">
        <a class="btn btn-outline-dark" href="{% url 'day_view' year=year month=month day=prev_day %}">Wczoraj</a>
        <button class="btn btn-outline-dark disabled">Harmonogram na: {{today}}</button>
        <a class="btn btn-outline-dark" href="{% url 'day_view' year=year month=month day=next_day %}">Jutro</a>
        </div>
    <hr>

    <table class="table table-striped table-bordered text-center">
        <thead class="table-dark">
            <tr>
                <th>Godzina</th>
                <th>1</th>
                <th>2</th>
                <th>P1</th>
                <th>P2</th>
                <th>3</th>
                <th>4</th>
                <th>5</th>
            </tr>
        </thead>
        <tbody>
            {% for hour, events in hourly_events.items %}
            <tr>
                <td class="table-dark fw-bold">{{ hour }}</td>
                {% for stol in "1234567" %}
                <td>
                    {% for e in events %}
                        {% if e.event.table == stol %}
                            <button type="button" class="btn btn-sm btn-success" 
                                    data-bs-toggle="modal" data-bs-target="#eventModal" 
                                    data-event-user="{{ e.event.user.last_name }} {{ e.event.user.first_name }}"
                                    data-event-user-id="{{ e.event.user.id }}"
                                    data-event-place="{{ e.event.get_place_display }}"
                                    data-event-table="{{ e.event.get_table_display }}"
                                    data-event-time="{{ e.event.start_time|time:'H:i' }} - {{ e.event.end_time|time:'H:i' }}"
                                    data-event-edit-url="{{ e.edit_url }}"
                                    data-bs-toggle="tooltip"
                                    title="{{ e.event.user.last_name }} {{ e.event.user.first_name }} - {{ e.event.get_place_display }} - {{ e.event.get_table_display }} - ({{ e.event.start_time|time:"H:i" }} - {{ e.event.end_time|time:"H:i" }})">
                                {{ event.start_time|time:"H:i" }}
                            </button>
                        {% endif %}
                    {% endfor %}
                </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% include "lutnia_app/addons/modal.html" %}

{% endblock %}

lutnia/lutnia_app/templates/lutnia_app/day_view2_withspan.html
{% extends "lutnia_app/base.html" %}

{% block content %}
<div class="container">
    <hr>
    <div class="btn-group d-flex">
    <a class="btn btn-outline-dark" href="{% url 'day_view' year=year month=month day=prev_day %}">Wczoraj</a>
    <a class="btn btn-outline-dark" href="{% url 'event_new' %}">Rezerwacja</a>
    <a class="btn btn-outline-dark" href="{% url 'day_view' year=year month=month day=next_day %}">Jutro</a>
    </div>
    <hr>
    <h3 class="text-center my-3">{{today}}</h3>
    {% for h in hourly_events.items%}
    
    {% endfor %}
    {% for ev in events %}
        {% if ev.get_place_display == "Moniuszki" %}
            {% if ev.table == "1" %}
                {{ev.table}}
                {{ev.start_time}}
            {% else %}
                {{ev.table}}
            {% endif %}
        {% else %}
            {{ev.get_place_display}}
        {% endif %}
    {% endfor %}
    <table class="table table-striped table-bordered text-center">
    <thead class="table-dark">
        <tr>
            <th>Godzina</th>
            {% for stol in "1234567" %}
                <th>{{ stol }}</th>  <!-- Dynamically render a header for each table -->
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for hour, events in hourly_events.items %}
            <tr>

                <td class="table-dark fw-bold">{{ hour }}</td>
                
                {% for stol in "1234567" %}
                    {% with event_found=False %}
                        {% for e in events %}
                            {% if e.event.table == stol and not event_found %}
                                <td rowspan="{{ e.rowspan }}">
                                       <a href="{{ e.edit_url }}" class="event-dot link-underline link-underline-opacity-0" data-bs-toggle="tooltip"
                                       title="{{ e.event.user.last_name }} {{ e.event.user.first_name }} - {{ e.event.get_place_display }} - {{ e.event.get_table_display }} - {{ e.event.table }} - ({{ e.event.start_time|time:"H:i" }} - {{ e.event.end_time|time:"H:i" }})">
                                        &#128994;
                                    </a>
                                </td>
                                {% with event_found=True %}
                                {% endwith %}
                            {% endif %}
                        {% endfor %}

                        {% if not event_found %}
                             <!-- Only render an empty <td> if no event was found for this table -->
                        {% endif %}
                    {% endwith %}
                {% endfor %}
            </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

lutnia/lutnia_app/templates/lutnia_app/edit_profile.html
{% extends "lutnia_app/base.html" %}
{% load crispy_forms_tags %}

{% block content %}


    <div class="card">
    <div class="card-header shadow-lg text-center"><h5>Edycja Profilu</h5></div>
    <div class="card-body">   
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ u_form|crispy }}
    {{ p_form|crispy }}
    </div>
    <div class="d-flex card-footer">
    <button type="submit" class="btn btn-outline-success">Zapisz</button>
    </div>
    </form>
    </div>
    
    

{% endblock %}

lutnia/lutnia_app/templates/lutnia_app/event_confirm_delete.html
{% extends "lutnia_app/base.html" %}  

{% block content %}

  <form method="post">
    {% csrf_token %}
    <div class="card border-danger text-center text-danger">
    <div class="card-header"><h2>Potwierdzenie</h2></div>
    <div class="card-body text-danger">
        <h5 class="card-title">Napewno skasowac rezerwacje?</h5>
        <hr>
        <p class="card-text">{{ event }}</p>
    </div>
        <div class="d-grid card-footer">
            <div class="btn-group" role="group" aria-label="Basic example">
            <button type="submit" class="btn btn-outline-danger">Tak</button>
            <a href="{% url 'event_edit' event.id %}" class="btn btn-outline-secondary">Nie</a>
            </div>
        </div>
    </div>
    
    
    
  </form>
{% endblock %}

lutnia/lutnia_app/templates/lutnia_app/excersises.html
{% extends "lutnia_app/base.html" %}
{% block content %}
<h1>W budowie</h1>
<h5>Do uzgodnienia</h5>
<ul>
    <li>wybierz tabele</li>
    <li>na zakonczenie cwiczen wpisz wyniki</li>
    <li>np: tabela nr.1</li>
    <li>dzien 1 data: ...</li>
    <li>Uklad 1 - ilosc podejsc: 6</li>
</ul>
{% endblock content %}

lutnia/lutnia_app/templates/lutnia_app/index.html
{% extends "lutnia_app/base.html" %}

{% block content %}
    <div class="card mb-3">
    <img src="/media/logo/lutnia_main_image.jpg" class="card-img-top" alt="main_image">
    <div class="card-body text-center">
        <h5 class="card-title">TS Lutnia - Akademia Snookera</h5>
        <p class="card-text">Adres: Moniuszki 15, 95-050 Konstantynów Łódzki</p>
        <p class="card-text"><small class="text-body-secondary">Telefon: 609 049 257</small></p>
    </div>
    <div class="card-footer text-body-secondary text-center">
        <a href="https://www.facebook.com/tslutnia/"  target="_blank"><img src="media/logo/Facebook_Logo_Primary.png" alt="FB" style="width:4%;"></a>
        <a href="https://www.youtube.com/@akademia-snookera-kts-lutnia"  target="_blank"><img src="media/logo/yt_icon_rgb.png" alt="YT" style="width:15%; padding-right: 5%; padding-left: 5%;"></a>
        <a href="https://maps.app.goo.gl/Sv8JWUJVU1weWX1A7"  target="_blank"><img src="media/logo/maps.png" alt="Maps" style="width:3%;"></a>
    </div>
    </div>
{% endblock content %}

lutnia/lutnia_app/templates/lutnia_app/my_login.html
{% extends "lutnia_app/base.html" %}
{% load crispy_forms_tags %} 

{% block content %}
<div class="card">
    <form method="post">
    {% csrf_token %}
        
            <div class="card-header">
                <h6 class="card-text text-center">Logowanie</h6>
            </div>
            <div class="card-body">
                {% crispy loginform %}
                <button type="submit" class="btn btn-primary">Zaloguj</button>
            </div>
        
    </form>
    <a href="accounts/password_reset">Resetuj haslo</a>
    <div class="card-footer text-body-secondary">
        <a class="btn btn-secondary" href="{% url 'register' %}">Nie masz konta? Zarejestruj sie</a>
    </div>
</div>

{% endblock content %}

lutnia/lutnia_app/templates/lutnia_app/register.html
{% extends "lutnia_app/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="card">
        <form method="post">
        {% csrf_token %}
            <div class="card-header">
                <h2 class="card-text text-center">Rejestracja</h2>
            </div>
            <div class="card-body">
                {% crispy registerform %}
                <button type="submit" class="btn btn-primary">Zarejestruj</button>
            </div>
        </form>
</div>
{% endblock content %}

lutnia/lutnia_app/templates/lutnia_app/stats.html
{% extends "lutnia_app/base.html" %}
{% block content %}
<h1>W budowie</h1>
<h5>Do uzgodnienia</h5>

<ul>
    <li>Ilosc godzin w tygodniu lub miesiacu</li>
    <li>Ilosc cwiczen</li>
    <li>Lista tabel w cwiczeniach</li>
    <li>Staty na dana tabele. np: tabela nr1 ilosc podejsc lub/oraz ilosc thafien</li>
    <li>Procent trafien na dana tabele</li>
    <li>Sparingi? np. ilosc frejmow i kto wygral</li>
</ul>
<div class="card">
    <p class="card-header">Przykładowa tabela z ćwiczeń</p>
    <table class="table">
    <thead>
    <th>Ilość godzin</th>
    <th>Ilość ćwiczeń</th>
    <th>Ilość podejść</th>
    <th>Ilość trafień</th>
    <th>Procent</th>
    </thead>
    <tbody>
        <td>3</td>
        <td>1</td>
        <td>1</td>
        <td>3</td>
        <td>90%</td>
    </tbody>
    </table> 
</div>

<p>Pewnie jakies grafy typu pie chart albo cos w tym stylu zeby pokazac staty</p>


<h5>Jesli jest jakis turniej mozna rowniez dodac tabele zawodnikow i staty z meczow</h5>
<div class="card">
    <p class="card-header">Przykładowa tabela turnieju</p>
  <table class="table table-bordered">
    <tbody>
        <tr>
            <td>zawodnik 1</td>
            <td rowspan="2">wygrany</td>
        </tr>
        <tr>
            <td>zawodnik 2</td>
        </tr>
        
        <tr>
            <td>zawodnik 3</td>
            <td rowspan="2">wygrany</td>
            <td rowspan="4">wygrany</td>
        </tr>
        <tr>
            <td>zawodnik 4</td>
        </tr>
        <tr>
            
        </tr>
    </tbody>
</table>  
</div>
<hr>
<div class="card">
    <p class="card-header">Przykładowa tabela z meczu</p>
  <table class="table">
    <thead>
        <th>Mecz</th>
        <th>zawodnik 1</th>
        <th>zawodnik 2</th>
        <th>Frame</th>
        <th>Wynik</th>    
    </thead>
    <tbody>
        <td>PORS3</td>
        <td>Zenek</td>
        <td>Karol</td>
        <td>1</td>
        <td>65-38</td>
    </tbody>
</table>  
</div>

{% endblock content %}